# Generated by Django 5.2.15 on 2026-06-22 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='beneficiaires.beneficiaire')),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='programmes.cohorte')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('beneficiaire', 'cohorte')},
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné'), ('en_attente_valid', 'En attente de validation')], default='en_cours', max_length=25)),
                ('commentaire', models.TextField(blank=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='programmes.etape')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='inscriptions.inscription')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['etape__ordre'],
                'unique_together': {('inscription', 'etape')},
            },
        ),
    ]
