# Generated by Django 5.2.15 on 2026-06-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviInsertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalon', models.CharField(choices=[('3_mois', 'Suivi 3 mois'), ('6_mois', 'Suivi 6 mois'), ('12_mois', 'Suivi 12 mois')], max_length=10)),
                ('statut_insertion', models.CharField(choices=[('emploi_salarie', 'Emploi salarié'), ('entrepreneuriat', 'Entrepreneuriat'), ('formation', 'Formation continue'), ('sans_solution', 'Sans solution'), ('non_repondu', 'Non répondu')], default='non_repondu', max_length=20)),
                ('date_suivi', models.DateField(auto_now_add=True)),
                ('date_relance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_insertion', to='beneficiaires.beneficiaire')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_insertion', to='programmes.programme')),
            ],
            options={
                'unique_together': {('beneficiaire', 'programme', 'jalon')},
            },
        ),
    ]
