# Generated by Django 5.2.15 on 2026-06-22 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('insertion', 'Insertion / Emploi'), ('incubation', 'Incubation / Entrepreneuriat'), ('education', 'Éducation'), ('conseil', 'Conseil / Accompagnement')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('localite', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('capacite', models.PositiveIntegerField(default=30)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to='programmes.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('validation_requise', models.BooleanField(default=False)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='programmes.programme')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('programme', 'ordre')},
            },
        ),
    ]
