# Generated by Django 5.2.15 on 2026-06-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('institution', 'Institution publique'), ('fondation', 'Fondation'), ('agence', 'Agence de coopération'), ('entreprise', 'Entreprise privée'), ('autre', 'Autre')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pays', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_debut', models.DateField()),
                ('echeance', models.DateField(blank=True, null=True)),
                ('convention_ref', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='financements.bailleur')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='programmes.programme')),
            ],
        ),
    ]
