# Generated by Django 5.2.15 on 2026-06-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_doc', models.CharField(choices=[('cv', 'CV'), ('piece_identite', "Pièce d'identité"), ('certificat', 'Certificat'), ('photo', 'Photo'), ('livrable', 'Livrable'), ('rapport', 'Rapport'), ('convention', 'Convention'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaires.beneficiaire')),
                ('progression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inscriptions.progression')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaires.structure')),
            ],
        ),
    ]
