# Generated by Django 5.2.15 on 2026-06-22 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localite', models.CharField(blank=True, max_length=200)),
                ('quartier', models.CharField(blank=True, max_length=200)),
                ('niveau_etudes', models.CharField(blank=True, max_length=100)),
                ('statut_pro', models.CharField(blank=True, choices=[('etudiant', 'Étudiant'), ('demandeur_emploi', "Demandeur d'emploi"), ('entrepreneur', 'Entrepreneur'), ('salarie', 'Salarié'), ('sans_emploi', 'Sans emploi')], max_length=20)),
                ('experience', models.TextField(blank=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_tel', models.CharField(blank=True, max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='pieces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembreStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('porteur', 'Porteur de projet'), ('cofondateur', 'Co-fondateur'), ('membre', 'Membre'), ('representant', 'Représentant')], default='membre', max_length=20)),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaires.beneficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('association', 'Association'), ('entreprise', 'Entreprise incubée'), ('etablissement', 'Établissement scolaire')], max_length=20)),
                ('secteur', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_nom', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_tel', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membres', models.ManyToManyField(related_name='structures', through='beneficiaires.MembreStructure', to='beneficiaires.beneficiaire')),
            ],
        ),
        migrations.AddField(
            model_name='membrestructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiaires.structure'),
        ),
        migrations.AlterUniqueTogether(
            name='membrestructure',
            unique_together={('beneficiaire', 'structure')},
        ),
    ]
