# Generated by Django 5.2.15 on 2026-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10),
        ),
    ]
