# Generated by Django 5.2.15 on 2026-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0002_alter_beneficiaire_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='niveau_professionnalisation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Niveau de professionnalisation'),
        ),
    ]
