# Generated by Django 5.2.15 on 2026-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaires', '0003_structure_niveau_professionnalisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='source',
            field=models.CharField(choices=[('manuel', 'Saisie manuelle'), ('asso_pro', 'ASSO-PRO'), ('sageo', 'SAGEO/IGBS')], default='manuel', max_length=20, verbose_name='Source'),
        ),
    ]
